project_id = "rliefaciadhxjjynuyod"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.stripe-account-info]
verify_jwt = false